package org.radioplayer.automotive.designsystem.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class ColorSchemeOEM(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val surfaceTint: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainer: Color,
    val surfaceContainerSelected: Color,
    val onSurfaceContainerSelected: Color,
    val surfaceContainerTranslucent: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val aaosScrimHigh: Color,
    val aaosScrimMedium: Color,
    val aaosScrimLow: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val blue: Color,
    val onBlue: Color,
    val blueContainer: Color,
    val onBlueContainer: Color,
    val red: Color,
    val onRed: Color,
    val redContainer: Color,
    val onRedContainer: Color,
    val green: Color,
    val onGreen: Color,
    val greenContainer: Color,
    val onGreenContainer: Color,
    val yellow: Color,
    val onYellow: Color,
    val yellowContainer: Color,
    val onYellowContainer: Color,
    val accentAuto: Color,
    val onAccentAuto: Color,
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
    val redFixed: Color,
    val onRedFixed: Color,
    val surfaceContainerOverlay: Color,
)

@Immutable
data class ColorSchemeOverrides(
    val primary: Color? = null,
    val onPrimary: Color? = null,
    val primaryContainer: Color? = null,
    val onPrimaryContainer: Color? = null,
    val inversePrimary: Color? = null,
    val secondary: Color? = null,
    val onSecondary: Color? = null,
    val secondaryContainer: Color? = null,
    val onSecondaryContainer: Color? = null,
    val tertiary: Color? = null,
    val onTertiary: Color? = null,
    val tertiaryContainer: Color? = null,
    val onTertiaryContainer: Color? = null,
    val error: Color? = null,
    val onError: Color? = null,
    val errorContainer: Color? = null,
    val onErrorContainer: Color? = null,
    val surface: Color? = null,
    val onSurface: Color? = null,
    val surfaceVariant: Color? = null,
    val onSurfaceVariant: Color? = null,
    val inverseSurface: Color? = null,
    val inverseOnSurface: Color? = null,
    val surfaceTint: Color? = null,
    val surfaceDim: Color? = null,
    val surfaceBright: Color? = null,
    val surfaceContainer: Color? = null,
    val surfaceContainerSelected: Color? = null,
    val onSurfaceContainerSelected: Color? = null,
    val surfaceContainerTranslucent: Color? = null,
    val surfaceContainerLowest: Color? = null,
    val surfaceContainerLow: Color? = null,
    val surfaceContainerHigh: Color? = null,
    val surfaceContainerHighest: Color? = null,
    val outline: Color? = null,
    val outlineVariant: Color? = null,
    val scrim: Color? = null,
    val aaosScrimHigh: Color? = null,
    val aaosScrimMedium: Color? = null,
    val aaosScrimLow: Color? = null,
    val textPrimary: Color? = null,
    val textSecondary: Color? = null,
    val textTertiary: Color? = null,
    val blue: Color? = null,
    val onBlue: Color? = null,
    val blueContainer: Color? = null,
    val onBlueContainer: Color? = null,
    val red: Color? = null,
    val onRed: Color? = null,
    val redContainer: Color? = null,
    val onRedContainer: Color? = null,
    val green: Color? = null,
    val onGreen: Color? = null,
    val greenContainer: Color? = null,
    val onGreenContainer: Color? = null,
    val yellow: Color? = null,
    val onYellow: Color? = null,
    val yellowContainer: Color? = null,
    val onYellowContainer: Color? = null,
    val accentAuto: Color? = null,
    val onAccentAuto: Color? = null,
    val primaryFixed: Color? = null,
    val primaryFixedDim: Color? = null,
    val onPrimaryFixed: Color? = null,
    val onPrimaryFixedVariant: Color? = null,
    val secondaryFixed: Color? = null,
    val secondaryFixedDim: Color? = null,
    val onSecondaryFixed: Color? = null,
    val onSecondaryFixedVariant: Color? = null,
    val tertiaryFixed: Color? = null,
    val tertiaryFixedDim: Color? = null,
    val onTertiaryFixed: Color? = null,
    val onTertiaryFixedVariant: Color? = null,
    val redFixed: Color? = null,
    val onRedFixed: Color? = null,
    val surfaceContainerOverlay: Color? = null,
)

fun lightColorSchemeOEM(
    palette: PaletteTokens = DefaultPaletteTokens,
    overrides: ColorSchemeOverrides = ColorSchemeOverrides()
): ColorSchemeOEM {
    val tokens = lightColorTokens(palette)

    return ColorSchemeOEM(
        primary                     = overrides.primary ?: tokens.Primary,
        onPrimary                   = overrides.onPrimary ?: tokens.OnPrimary,
        primaryContainer            = overrides.primaryContainer ?: tokens.PrimaryContainer,
        onPrimaryContainer          = overrides.onPrimaryContainer ?: tokens.OnPrimaryContainer,
        inversePrimary              = overrides.inversePrimary ?: tokens.InversePrimary,
        secondary                   = overrides.secondary ?: tokens.Secondary,
        onSecondary                 = overrides.onSecondary ?: tokens.OnSecondary,
        secondaryContainer          = overrides.secondaryContainer ?: tokens.SecondaryContainer,
        onSecondaryContainer        = overrides.onSecondaryContainer ?: tokens.OnSecondaryContainer,
        tertiary                    = overrides.tertiary ?: tokens.Tertiary,
        onTertiary                  = overrides.onTertiary ?: tokens.OnTertiary,
        tertiaryContainer           = overrides.tertiaryContainer ?: tokens.TertiaryContainer,
        onTertiaryContainer         = overrides.onTertiaryContainer ?: tokens.OnTertiaryContainer,
        error                       = overrides.error ?: tokens.Error,
        onError                     = overrides.onError ?: tokens.OnError,
        errorContainer              = overrides.errorContainer ?: tokens.ErrorContainer,
        onErrorContainer            = overrides.onErrorContainer ?: tokens.OnErrorContainer,
        surface                     = overrides.surface ?: tokens.Surface,
        onSurface                   = overrides.onSurface ?: tokens.OnSurface,
        surfaceVariant              = overrides.surfaceVariant ?: tokens.SurfaceVariant,
        onSurfaceVariant            = overrides.onSurfaceVariant ?: tokens.OnSurfaceVariant,
        inverseSurface              = overrides.inverseSurface ?: tokens.InverseSurface,
        inverseOnSurface            = overrides.inverseOnSurface ?: tokens.InverseOnSurface,
        surfaceTint                 = overrides.surfaceTint ?: tokens.SurfaceTint,
        surfaceDim                  = overrides.surfaceDim ?: tokens.SurfaceDim,
        surfaceBright               = overrides.surfaceBright ?: tokens.SurfaceBright,
        surfaceContainer            = overrides.surfaceContainer ?: tokens.SurfaceContainer,
        surfaceContainerSelected    = overrides.surfaceContainerSelected ?: tokens.SurfaceContainerSelected,
        onSurfaceContainerSelected  = overrides.onSurfaceContainerSelected ?: tokens.OnSurfaceContainerSelected,
        surfaceContainerTranslucent = overrides.surfaceContainerTranslucent ?: tokens.SurfaceContainerTranslucent,
        surfaceContainerLowest      = overrides.surfaceContainerLowest ?: tokens.SurfaceContainerLowest,
        surfaceContainerLow         = overrides.surfaceContainerLow ?: tokens.SurfaceContainerLow,
        surfaceContainerHigh        = overrides.surfaceContainerHigh ?: tokens.SurfaceContainerHigh,
        surfaceContainerHighest     = overrides.surfaceContainerHighest ?: tokens.SurfaceContainerHighest,
        outline                     = overrides.outline ?: tokens.Outline,
        outlineVariant              = overrides.outlineVariant ?: tokens.OutlineVariant,
        scrim                       = overrides.scrim ?: tokens.Scrim,
        aaosScrimHigh               = overrides.aaosScrimHigh ?: tokens.AaosScrimHigh,
        aaosScrimMedium             = overrides.aaosScrimMedium ?: tokens.AaosScrimMedium,
        aaosScrimLow                = overrides.aaosScrimLow ?: tokens.AaosScrimLow,
        textPrimary                 = overrides.textPrimary ?: tokens.TextPrimary,
        textSecondary               = overrides.textSecondary ?: tokens.TextSecondary,
        textTertiary                = overrides.textTertiary ?: tokens.TextTertiary,
        blue                        = overrides.blue ?: tokens.Blue,
        onBlue                      = overrides.onBlue ?: tokens.OnBlue,
        blueContainer               = overrides.blueContainer ?: tokens.BlueContainer,
        onBlueContainer             = overrides.onBlueContainer ?: tokens.OnBlueContainer,
        red                         = overrides.red ?: tokens.Red,
        onRed                       = overrides.onRed ?: tokens.OnRed,
        redContainer                = overrides.redContainer ?: tokens.RedContainer,
        onRedContainer              = overrides.onRedContainer ?: tokens.OnRedContainer,
        green                       = overrides.green ?: tokens.Green,
        onGreen                     = overrides.onGreen ?: tokens.OnGreen,
        greenContainer              = overrides.greenContainer ?: tokens.GreenContainer,
        onGreenContainer            = overrides.onGreenContainer ?: tokens.OnGreenContainer,
        yellow                      = overrides.yellow ?: tokens.Yellow,
        onYellow                    = overrides.onYellow ?: tokens.OnYellow,
        yellowContainer             = overrides.yellowContainer ?: tokens.YellowContainer,
        onYellowContainer           = overrides.onYellowContainer ?: tokens.OnYellowContainer,
        accentAuto                  = overrides.accentAuto ?: tokens.AccentAuto,
        onAccentAuto                = overrides.onAccentAuto ?: tokens.OnAccentAuto,
        primaryFixed                = overrides.primaryFixed ?: tokens.PrimaryFixed,
        primaryFixedDim             = overrides.primaryFixedDim ?: tokens.PrimaryFixedDim,
        onPrimaryFixed              = overrides.onPrimaryFixed ?: tokens.OnPrimaryFixed,
        onPrimaryFixedVariant       = overrides.onPrimaryFixedVariant ?: tokens.OnPrimaryFixedVariant,
        secondaryFixed              = overrides.secondaryFixed ?: tokens.SecondaryFixed,
        secondaryFixedDim           = overrides.secondaryFixedDim ?: tokens.SecondaryFixedDim,
        onSecondaryFixed            = overrides.onSecondaryFixed ?: tokens.OnSecondaryFixed,
        onSecondaryFixedVariant     = overrides.onSecondaryFixedVariant ?: tokens.OnSecondaryFixedVariant,
        tertiaryFixed               = overrides.tertiaryFixed ?: tokens.TertiaryFixed,
        tertiaryFixedDim            = overrides.tertiaryFixedDim ?: tokens.TertiaryFixedDim,
        onTertiaryFixed             = overrides.onTertiaryFixed ?: tokens.OnTertiaryFixed,
        onTertiaryFixedVariant      = overrides.onTertiaryFixedVariant ?: tokens.OnTertiaryFixedVariant,
        redFixed                    = overrides.redFixed ?: tokens.RedFixed,
        onRedFixed                  = overrides.onRedFixed ?: tokens.OnRedFixed,
        surfaceContainerOverlay     = overrides.surfaceContainerOverlay ?: tokens.SurfaceContainerOverlay,
    )

}

fun darkColorSchemeOEM(
    palette: PaletteTokens = DefaultPaletteTokens,
    overrides: ColorSchemeOverrides  = ColorSchemeOverrides()
): ColorSchemeOEM {
    val tokens = darkColorTokens(palette)

    return ColorSchemeOEM(
        primary                     = overrides.primary ?: tokens.Primary,
        onPrimary                   = overrides.onPrimary ?: tokens.OnPrimary,
        primaryContainer            = overrides.primaryContainer ?: tokens.PrimaryContainer,
        onPrimaryContainer          = overrides.onPrimaryContainer ?: tokens.OnPrimaryContainer,
        inversePrimary              = overrides.inversePrimary ?: tokens.InversePrimary,
        secondary                   = overrides.secondary ?: tokens.Secondary,
        onSecondary                 = overrides.onSecondary ?: tokens.OnSecondary,
        secondaryContainer          = overrides.secondaryContainer ?: tokens.SecondaryContainer,
        onSecondaryContainer        = overrides.onSecondaryContainer ?: tokens.OnSecondaryContainer,
        tertiary                    = overrides.tertiary ?: tokens.Tertiary,
        onTertiary                  = overrides.onTertiary ?: tokens.OnTertiary,
        tertiaryContainer           = overrides.tertiaryContainer ?: tokens.TertiaryContainer,
        onTertiaryContainer         = overrides.onTertiaryContainer ?: tokens.OnTertiaryContainer,
        error                       = overrides.error ?: tokens.Error,
        onError                     = overrides.onError ?: tokens.OnError,
        errorContainer              = overrides.errorContainer ?: tokens.ErrorContainer,
        onErrorContainer            = overrides.onErrorContainer ?: tokens.OnErrorContainer,
        surface                     = overrides.surface ?: tokens.Surface,
        onSurface                   = overrides.onSurface ?: tokens.OnSurface,
        surfaceVariant              = overrides.surfaceVariant ?: tokens.SurfaceVariant,
        onSurfaceVariant            = overrides.onSurfaceVariant ?: tokens.OnSurfaceVariant,
        inverseSurface              = overrides.inverseSurface ?: tokens.InverseSurface,
        inverseOnSurface            = overrides.inverseOnSurface ?: tokens.InverseOnSurface,
        surfaceTint                 = overrides.surfaceTint ?: tokens.SurfaceTint,
        surfaceDim                  = overrides.surfaceDim ?: tokens.SurfaceDim,
        surfaceBright               = overrides.surfaceBright ?: tokens.SurfaceBright,
        surfaceContainer            = overrides.surfaceContainer ?: tokens.SurfaceContainer,
        surfaceContainerSelected    = overrides.surfaceContainerSelected ?: tokens.SurfaceContainerSelected,
        onSurfaceContainerSelected  = overrides.onSurfaceContainerSelected ?: tokens.OnSurfaceContainerSelected,
        surfaceContainerTranslucent = overrides.surfaceContainerTranslucent ?: tokens.SurfaceContainerTranslucent,
        surfaceContainerLowest      = overrides.surfaceContainerLowest ?: tokens.SurfaceContainerLowest,
        surfaceContainerLow         = overrides.surfaceContainerLow ?: tokens.SurfaceContainerLow,
        surfaceContainerHigh        = overrides.surfaceContainerHigh ?: tokens.SurfaceContainerHigh,
        surfaceContainerHighest     = overrides.surfaceContainerHighest ?: tokens.SurfaceContainerHighest,
        outline                     = overrides.outline ?: tokens.Outline,
        outlineVariant              = overrides.outlineVariant ?: tokens.OutlineVariant,
        scrim                       = overrides.scrim ?: tokens.Scrim,
        aaosScrimHigh               = overrides.aaosScrimHigh ?: tokens.AaosScrimHigh,
        aaosScrimMedium             = overrides.aaosScrimMedium ?: tokens.AaosScrimMedium,
        aaosScrimLow                = overrides.aaosScrimLow ?: tokens.AaosScrimLow,
        textPrimary                 = overrides.textPrimary ?: tokens.TextPrimary,
        textSecondary               = overrides.textSecondary ?: tokens.TextSecondary,
        textTertiary                = overrides.textTertiary ?: tokens.TextTertiary,
        blue                        = overrides.blue ?: tokens.Blue,
        onBlue                      = overrides.onBlue ?: tokens.OnBlue,
        blueContainer               = overrides.blueContainer ?: tokens.BlueContainer,
        onBlueContainer             = overrides.onBlueContainer ?: tokens.OnBlueContainer,
        red                         = overrides.red ?: tokens.Red,
        onRed                       = overrides.onRed ?: tokens.OnRed,
        redContainer                = overrides.redContainer ?: tokens.RedContainer,
        onRedContainer              = overrides.onRedContainer ?: tokens.OnRedContainer,
        green                       = overrides.green ?: tokens.Green,
        onGreen                     = overrides.onGreen ?: tokens.OnGreen,
        greenContainer              = overrides.greenContainer ?: tokens.GreenContainer,
        onGreenContainer            = overrides.onGreenContainer ?: tokens.OnGreenContainer,
        yellow                      = overrides.yellow ?: tokens.Yellow,
        onYellow                    = overrides.onYellow ?: tokens.OnYellow,
        yellowContainer             = overrides.yellowContainer ?: tokens.YellowContainer,
        onYellowContainer           = overrides.onYellowContainer ?: tokens.OnYellowContainer,
        accentAuto                  = overrides.accentAuto ?: tokens.AccentAuto,
        onAccentAuto                = overrides.onAccentAuto ?: tokens.OnAccentAuto,
        primaryFixed                = overrides.primaryFixed ?: tokens.PrimaryFixed,
        primaryFixedDim             = overrides.primaryFixedDim ?: tokens.PrimaryFixedDim,
        onPrimaryFixed              = overrides.onPrimaryFixed ?: tokens.OnPrimaryFixed,
        onPrimaryFixedVariant       = overrides.onPrimaryFixedVariant ?: tokens.OnPrimaryFixedVariant,
        secondaryFixed              = overrides.secondaryFixed ?: tokens.SecondaryFixed,
        secondaryFixedDim           = overrides.secondaryFixedDim ?: tokens.SecondaryFixedDim,
        onSecondaryFixed            = overrides.onSecondaryFixed ?: tokens.OnSecondaryFixed,
        onSecondaryFixedVariant     = overrides.onSecondaryFixedVariant ?: tokens.OnSecondaryFixedVariant,
        tertiaryFixed               = overrides.tertiaryFixed ?: tokens.TertiaryFixed,
        tertiaryFixedDim            = overrides.tertiaryFixedDim ?: tokens.TertiaryFixedDim,
        onTertiaryFixed             = overrides.onTertiaryFixed ?: tokens.OnTertiaryFixed,
        onTertiaryFixedVariant      = overrides.onTertiaryFixedVariant ?: tokens.OnTertiaryFixedVariant,
        redFixed                    = overrides.redFixed ?: tokens.RedFixed,
        onRedFixed                  = overrides.onRedFixed ?: tokens.OnRedFixed,
        surfaceContainerOverlay     = overrides.surfaceContainerOverlay ?: tokens.SurfaceContainerOverlay,
    )
}